spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: ~
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
