spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true

auth:
  secret-key: learning-test-spring
  expiration-time: 3600000
