spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always

auth:
  secretKey: learning-test-spring
  validityInMilliseconds: 3_600_000

