TRUNCATE TABLE THEME;
TRUNCATE TABLE RESERVATION;
TRUNCATE TABLE MEMBER;
TRUNCATE TABLE SCHEDULE;

ALTER TABLE THEME ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE RESERVATION ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE MEMBER ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE SCHEDULE ALTER COLUMN ID RESTART WITH 1;